import streamlit as st
import tensorflow as tf
import numpy as np
from PIL import Image

# --- 1. Page Configuration ---
st.set_page_config(page_title="Pro Ag-Clinic AI", page_icon="🌿", layout="wide")

# --- 2. Advanced CSS ---
st.markdown("""
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Segoe+UI:wght@400;700&display=swap');
    
    html, body, [class*="css"] {
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    }

    .report-container {
        background-color: #ffffff !important;
        color: #111111 !important;
        padding: 30px;
        border-radius: 15px;
        border-left: 12px solid #1b5e20;
        box-shadow: 0px 10px 30px rgba(0,0,0,0.2);
        line-height: 1.6;
        text-align: left;
    }

    .report-container h2, .report-container h3, .report-container h4 {
        color: #1b5e20 !important;
        margin-top: 20px;
        font-weight: bold;
    }

    .report-container b {
        color: #000000 !important;
    }

    .stButton>button {
        width: 100%;
        background-color: #1b5e20;
        color: white;
        font-size: 18px;
        font-weight: bold;
        padding: 15px;
        border-radius: 10px;
    }
    </style>
    """, unsafe_allow_html=True)

# --- 3. Model Loading ---
@st.cache_resource
def load_agri_model():
    return tf.keras.models.load_model('Fplant_model.keras')

model = load_agri_model()

# --- 4. Class Mapping ---
class_names = [
    "Pepper__bell___Bacterial_spot", "Pepper__bell___healthy",
    "Potato___Early_blight", "Potato___Late_blight", "Potato___healthy",
    "Tomato_Bacterial_spot", "Tomato_Early_blight", "Tomato_Late_blight",
    "Tomato_Leaf_Mold", "Tomato_Septoria_leaf_spot",
    "Tomato_Spider_mites_Two_spotted_spider_mite", "Tomato__Target_Spot",
    "Tomato__Tomato_YellowLeaf__Curl_Virus", "Tomato__Tomato_mosaic_virus",
    "Tomato_healthy"
]

# --- 5. Detailed Agronomic Logic (FIXED FOR MARKDOWN) ---
def get_detailed_report(disease, temp, soil, water, conf):
    disease_title = disease.replace("_", " ")
    
    # Header - MUST START AT FAR LEFT TO AVOID MARKDOWN CODE BLOCK
    html = f"""<div class="report-container">
<h2 style="text-align: center;">OFFICIAL AGRONOMIC DIAGNOSIS REPORT</h2>
<p style="text-align: center;">Generated by AI Consultant v3.0 | Precision Agriculture Division</p>
<hr>
<p><b>Primary Diagnosis:</b> {disease_title}</p>
<p><b>Statistical Confidence:</b> {conf*100:.2f}%</p>
<p><b>Field Conditions:</b> Temp: {temp}°C | Soil: {soil} | Irrigation: {water}</p>
<hr>"""

    if "healthy" in disease:
        html += """<h3>✅ Physiological Assessment: Optimal</h3>
<p>The analyzed specimen shows <b>excellent chlorophyll density</b> and no cellular degradation. The vascular system appears functional.</p>
<h4>Strategic Recommendations:</h4>
<ul>
<li><b>Nutritional Balance:</b> Maintain N-P-K ratios. Focus on Calcium-Boron applications during flowering.</li>
<li><b>Biostimulants:</b> Apply Amino Acids and Humic Acid to enhance root absorption efficiency.</li>
<li><b>Monitoring:</b> Scout the field every 48 hours for early pest egg clusters.</li>
</ul>"""

    elif "Late_blight" in disease:
        html += """<h3>🚨 Pathogen Alert: Late Blight (Phytophthora infestans)</h3>
<p><b>Etiology:</b> An oomycete pathogen that thrives in high humidity (>90%). It can destroy fields within 7-10 days.</p>
<h4>🛠️ Emergency Action Plan:</h4>
<p><b>1. Immediate Chemical Intervention:</b>
<ul>
<li><b>Metalaxyl-M + Mancozeb</b> (e.g., Ridomil Gold) at 250g/100L.</li>
<li><b>Cymoxanil + Famoxadone</b> for curative action on early lesions.</li>
<li><b>Propamocarb Hydrochloride</b> for root and stem protection.</li>
</ul></p>
<p><b>2. Field Management:</b>
<ul>
<li><b>Humidity:</b> Halt overhead irrigation immediately. Switch to drip.</li>
<li><b>Sanitation:</b> Remove and burn infected plants. Do NOT compost.</li>
<li><b>Airflow:</b> Increase plant spacing to reduce canopy moisture.</li>
</ul></p>"""

    elif "Spider_mites" in disease:
        html += """<h3>🕷️ Pest Analysis: Two-Spotted Spider Mite</h3>
<p><b>Observations:</b> Punctured leaf cells leading to chlorotic stippling. Mites feed on the abaxial surface.</p>
<h4>🛠️ Integrated Pest Management (IPM):</h4>
<p><b>1. Chemical Control:</b>
<ul>
<li><b>Abamectin 1.8% EC:</b> Apply at 50ml/100L. Ensure thorough coverage.</li>
<li><b>Spiromesifen:</b> Excellent for controlling eggs and nymphs.</li>
<li><b>Bifenazate:</b> For rapid knockdown of adults.</li>
</ul></p>
<p><b>2. Physical Control:</b>
<ul>
<li><b>Mist Spraying:</b> Increasing humidity inhibits mite reproduction.</li>
<li><b>Beneficials:</b> Encourage predatory mites like <i>Phytoseiulus persimilis</i>.</li>
</ul></p>"""

    elif "Virus" in disease or "mosaic" in disease or "YellowLeaf" in disease:
        html += """<h3>🚫 Pathological Assessment: Viral Colonization</h3>
<p><b>Technical Note:</b> Viruses are systemic. Once infected, there is no chemical cure for the plant tissue.</p>
<h4>🛠️ Control Strategy:</h4>
<p><b>1. Vector Management:</b> Control Whiteflies and Aphids.
<ul>
<li>Apply <b>Imidacloprid</b> or <b>Acetamiprid</b>.</li>
<li>Use yellow sticky traps for monitoring.</li>
</ul></p>
<p><b>2. Eradication:</b> Uproot infected plants immediately as they are reservoirs.</p>
<p><b>3. Hygiene:</b> Sterilize tools with 10% bleach solution.</p>"""

    else:
        html += f"""<h3>🍄 Diagnosis: {disease_title}</h3>
<p>Necrotic lesions likely caused by fungal/bacterial pathogens.</p>
<h4>🛠️ Expert Recommendations:</h4>
<ul>
<li><b>Fungicides:</b> Apply <b>Chlorothalonil</b> or <b>Azoxystrobin</b>.</li>
<li><b>Copper Treatment:</b> Apply <b>Copper Oxychloride</b> (300g/100L) for bacterial suppression.</li>
<li><b>Drainage:</b> Ensure no waterlogging to support natural immunity.</li>
</ul>"""

    # Environmental Context
    html += "<h4>🌍 Environmental Intelligence Factors:</h4>"
    if temp > 38:
        html += f"<p>⚠️ <b>Heat Stress ({temp}°C):</b> Apply <b>Potassium Silicate</b> to harden cell walls and reduce transpiration.</p>"
    
    if soil == "Clay" and water == "High":
        html += "<p>⚠️ <b>Soil Mechanics:</b> High risk of <b>Hypoxia</b> and root rot in heavy soil.</p>"
    elif soil == "Sandy" and water == "Low":
        html += "<p>💧 <b>Drought Stress:</b> Sandy soils drain rapidly. Plant is nearing wilting point.</p>"

    html += f"""<hr>
<p style="font-style: italic;"><b>Final Engineering Verdict:</b> Confidence level is {conf*100:.1f}%. Recommendation based on international agronomic protocols.</p>
</div>"""
    return html

# --- 6. App Layout ---
st.title("🌿 Professional Agriculture AI Clinic")
st.markdown("Detailed Pathological Analysis & Expert Consultation System")
st.markdown("---")

c1, c2 = st.columns([1, 1.4], gap="large")

with c1:
    st.subheader("📋 Input Field Data")
    uploaded_file = st.file_uploader("Upload Leaf Specimen (JPG/PNG)", type=["jpg","jpeg","png"])
    
    with st.expander("Environment Sensors (Manual Entry)"):
        t_input = st.slider("Ambient Temperature (°C)", 0, 55, 26)
        s_input = st.selectbox("Soil Composition", ["Clay", "Sandy", "Loamy", "Silty"])
        w_input = st.selectbox("Irrigation/Moisture Level", ["Low", "Medium", "High", "Waterlogged"])

with c2:
    st.subheader("🔍 Technical Analysis Report")
    if uploaded_file:
        img = Image.open(uploaded_file)
        st.image(img, width=400, caption="Sample ID: " + str(uploaded_file.name))
        
        if st.button("EXECUTE DEEP ANALYSIS"):
            with st.spinner('Accessing Agricultural Knowledge Base...'):
                # Process
                proc_img = img.convert("RGB").resize((224, 224))
                img_array = np.array(proc_img) / 255.0
                img_array = np.expand_dims(img_array, axis=0)
                
                # Predict
                raw_preds = model.predict(img_array, verbose=0)
                best_idx = np.argmax(raw_preds)
                best_conf = float(np.max(raw_preds))
                label = class_names[best_idx]
                
                # Success Info
                st.success(f"Pathogen Identified: {label.replace('___', ' | ')}")
                
                # Detailed Report Rendering
                full_report = get_detailed_report(label, t_input, s_input, w_input, best_conf)
                st.markdown(full_report, unsafe_allow_html=True)
    else:
        st.info("Awaiting leaf specimen for diagnosis...")

st.markdown("---")
st.caption("© 2026 Smart Agri-Systems | Expert Module | Precision Agriculture Division")
